### ISSUE TITLE
部分实验结果和论文不一致

### ISSUE THREAD

**Issue by byran-wang** [lym29/EasyHOI#6]
Hi @lym29 ，

非常感谢你的工作。

我已经在你提供的airplane.jpg， game-controller.jpg， coffee-1.png和coffee-2.jpg的data上将整个pipeline跑通了，并得到了最终结果。

airplane.jpg的结果：

https://github.com/user-attachments/assets/9bd8fad3-8407-4c89-8206-6a89b3d98ef1

game-controller.jpg的结果：

https://github.com/user-attachments/assets/c3ac4488-c035-468c-a223-1302866db4eb

coffee-1.png的结果：

https://github.com/user-attachments/assets/02ff2429-64c8-4a18-9664-95b2f102eca6

coffee-2.jpg的结果：

https://github.com/user-attachments/assets/2a2039a1-bb9e-4742-ad12-e3b9e7a4f0e4

game-controller.jpg， coffee-1.png的结果和论文一致，不过airplane.jpg和coffee-2.jpg和论文不一致，不一致的原因是什么啊？有哪个参数需要调整一下吗？

**Comment by lym29** [comment]
感谢关注！可以邮件发一下中间结果吗 lym29@connect.hku.hk 
我检查一下，下周会更新一个版本

**Comment by byran-wang** [comment]
已经将中间结果发送到你的邮箱中了哈，谢谢!

**Comment by lym29** [comment]
之前算contact point的部分随机性太大，目前更新了一个版本，可以试验一下

**Comment by byran-wang** [comment]
@lym29 
将代码更新到0b6853d，测试结果如下：
airplane.jpg的结果：

https://github.com/user-attachments/assets/bc3eddbc-6b78-45be-9e75-bea9d19d0ffb

coffee-1.png的结果：

https://github.com/user-attachments/assets/41e07e83-3e5e-41bf-9bb3-d4dbc9277a67

game-controller.jpg的结果：

https://github.com/user-attachments/assets/6a6baec8-6604-476e-a3b1-62501bee058d

coffee-2.jpg的结果：

https://github.com/user-attachments/assets/a24b461e-43b6-49ed-9dd7-0dcc6d25ac99

airplane和输入的图片基本一致，不过 coffee-1和game-controller拇指的位置和论文不一致，coffee-2手的姿态完全错了，这是什么原因啊？你本地可以复现论文的结果吗？

**Comment by byran-wang** [comment]
The code sometimes report the following errors for coffee-1:
Traceback (most recent call last):2590it [00:01, 2972.12it/s]         
  File "/home/simba/Documents/project/EasyHOI/src/optim_easyhoi.py", line 373, in main
    hoi_sync.run_handpose_global()
  File "/home/simba/Documents/project/EasyHOI/src/models/hoi_optim_module.py", line 860, in run_handpose_global
    loss.backward()
AttributeError: 'int' object has no attribute 'backward'

**Comment by lym29** [comment]
Coffee-2 我本地跑出来结果是这样：

![Image](https://github.com/user-attachments/assets/0498b1ac-4a39-446f-bb5e-a11375bbaff6)

**Comment by lym29** [comment]
是 cc8c01a

**Comment by 1nightzhangjh1** [comment]
Hello, I would like to ask how the final video that includes both hands and object meshes is generated, and why the result I obtained only contains the object.
